[package]
name = "aoc2015"
version = "0.1.0"
authors = ["Ritoban Roy-Chowdhury <ritobanrc@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
itertools = "0.9"
cgmath = "0.17"
md5 = "0.7"
regex = "1.3"
paste = "0.1.16"
json = "0.12.4"
